export const STORE_PROFILE_REQUEST = 'STORE_PROFILE_REQUEST';
export const STORE_PROFILE_REQUEST_SUCCESS = 'STORE_PROFILE_REQUEST_SUCCESS';
export const STORE_PROFILE_REQUEST_ERROR = 'STORE_PROFILE_REQUEST_ERROR';

export const STORE_EDIT_PROFILE_REQUEST = 'STORE_EDIT_PROFILE_REQUEST';
export const STORE_EDIT_PROFILE_REQUEST_SUCCESS = 'STORE_EDIT_PROFILE_REQUEST_SUCCESS';
export const STORE_EDIT_PROFILE_REQUEST_ERROR = 'STORE_EDIT_PROFILE_REQUEST_ERROR';
