export const STORE_CREATE_INGREDIENT_REQUEST = 'STORE_CREATE_INGREDIENT_REQUEST';
export const STORE_CREATE_INGREDIENT_REQUEST_SUCCESS = 'STORE_CREATE_INGREDIENT_REQUEST_SUCCESS';
export const STORE_CREATE_INGREDIENT_REQUEST_ERROR = 'STORE_CREATE_INGREDIENT_REQUEST_ERROR';

export const STORE_GET_INGREDIENTS_REQUEST = 'STORE_GET_INGREDIENTS_REQUEST';
export const STORE_GET_INGREDIENTS_REQUEST_SUCCESS = 'STORE_GET_INGREDIENTS_REQUEST_SUCCESS';
export const STORE_GET_INGREDIENTS_REQUEST_ERROR = 'STORE_GET_INGREDIENTS_REQUEST_ERROR';
