export const STORE_CREATE_PRODUCT_REQUEST = 'STORE_CREATE_PRODUCT_REQUEST';
export const STORE_CREATE_PRODUCT_REQUEST_SUCCESS = 'STORE_CREATE_PRODUCT_REQUEST_SUCCESS';
export const STORE_CREATE_PRODUCT_REQUEST_ERROR = 'STORE_CREATE_PRODUCT_REQUEST_ERROR';

export const STORE_ADD_PRODUCT_PICTURE_REQUEST = 'STORE_ADD_PRODUCT_PICTURE_REQUEST';
export const STORE_ADD_PRODUCT_PICTURE_REQUEST_SUCCESS = 'STORE_ADD_PRODUCT_PICTURE_REQUEST_SUCCESS';
export const STORE_ADD_PRODUCT_PICTURE_REQUEST_ERROR = 'STORE_ADD_PRODUCT_PICTURE_REQUEST_ERROR';

export const STORE_GET_PRODUCTS_REQUEST = 'STORE_GET_PRODUCTS_REQUEST';
export const STORE_GET_PRODUCTS_REQUEST_SUCCESS = 'STORE_GET_PRODUCTS_REQUEST_SUCCESS';
export const STORE_GET_PRODUCTS_REQUEST_ERROR = 'STORE_GET_PRODUCTS_REQUEST_ERROR';

export const STORE_DELETE_PRODUCT_REQUEST = 'STORE_DELETE_PRODUCT_REQUEST';
export const STORE_DELETE_PRODUCT_REQUEST_SUCCESS = 'STORE_DELETE_PRODUCT_REQUEST_SUCCESS';
export const STORE_DELETE_PRODUCT_REQUEST_ERROR = 'STORE_DELETE_PRODUCT_REQUEST_ERROR';

export const STORE_UPDATE_PRODUCT_REQUEST = 'STORE_UPDATE_PRODUCT_REQUEST';
export const STORE_UPDATE_PRODUCT_REQUEST_SUCCESS = 'STORE_UPDATE_PRODUCT_REQUEST_SUCCESS';
export const STORE_UPDATE_PRODUCT_REQUEST_ERROR = 'STORE_UPDATE_PRODUCT_REQUEST_ERROR';
