export const STORE_CREATE_SECTION_REQUEST = 'STORE_CREATE_SECTION_REQUEST';
export const STORE_CREATE_SECTION_REQUEST_SUCCESS = 'STORE_CREATE_SECTION_REQUEST_SUCCESS';
export const STORE_CREATE_SECTION_REQUEST_ERROR = 'STORE_CREATE_SECTION_REQUEST_ERROR';


export const STORE_GET_SECTIONS_REQUEST = 'STORE_GET_SECTIONS_REQUEST';
export const STORE_GET_SECTIONS_REQUEST_SUCCESS = 'STORE_GET_SECTIONS_REQUEST_SUCCESS';
export const STORE_GET_SECTIONS_REQUEST_ERROR = 'STORE_GET_SECTIONS_REQUEST_ERROR';

export const STORE_GET_SECTION_REQUEST = 'STORE_GET_SECTION_REQUEST';
export const STORE_GET_SECTION_REQUEST_SUCCESS = 'STORE_GET_SECTION_REQUEST_SUCCESS';
export const STORE_GET_SECTION_REQUEST_ERROR = 'STORE_GET_SECTION_REQUEST_ERROR';

export const STORE_DELETE_SECTION_REQUEST = 'STORE_DELETE_SECTION_REQUEST';
export const STORE_DELETE_SECTION_REQUEST_SUCCESS = 'STORE_DELETE_SECTION_REQUEST_SUCCESS';
export const STORE_DELETE_SECTION_REQUEST_ERROR = 'STORE_DELETE_SECTION_REQUEST_ERROR';

export const STORE_UPDATE_SECTION_REQUEST = 'STORE_UPDATE_SECTION_REQUEST';
export const STORE_UPDATE_SECTION_REQUEST_SUCCESS = 'STORE_UPDATE_SECTION_REQUEST_SUCCESS';
export const STORE_UPDATE_SECTION_REQUEST_ERROR = 'STORE_UPDATE_SECTION_REQUEST_ERROR';

