export const STORE_CREATE_VOUCHER_REQUEST = 'STORE_CREATE_VOUCHER_REQUEST';
export const STORE_CREATE_VOUCHER_REQUEST_SUCCESS = 'STORE_CREATE_VOUCHER_REQUEST_SUCCESS';
export const STORE_CREATE_VOUCHER_REQUEST_ERROR = 'STORE_CREATE_VOUCHER_REQUEST_ERROR';

export const STORE_GET_VOUCHERS_REQUEST = 'STORE_GET_VOUCHERS_REQUEST';
export const STORE_GET_VOUCHERS_REQUEST_SUCCESS = 'STORE_GET_VOUCHERS_REQUEST_SUCCESS';
export const STORE_GET_VOUCHERS_REQUEST_ERROR = 'STORE_GET_VOUCHERS_REQUEST_ERROR';

export const STORE_DELETE_VOUCHER_REQUEST = 'STORE_DELETE_VOUCHER_REQUEST';
export const STORE_DELETE_VOUCHER_REQUEST_SUCCESS = 'STORE_DELETE_VOUCHER_REQUEST_SUCCESS';
export const STORE_DELETE_VOUCHER_REQUEST_ERROR = 'STORE_DELETE_VOUCHER_REQUEST_ERROR';

