export const STORE_GET_ORDERS_REQUEST = 'STORE_GET_ORDERS_REQUEST';
export const STORE_GET_ORDERS_REQUEST_SUCCESS = 'STORE_GET_ORDERS_REQUEST_SUCCESS';
export const STORE_GET_ORDERS_REQUEST_ERROR = 'STORE_GET_ORDERS_REQUEST_ERROR';
