export const STORE_CREATE_KIOSK_REQUEST = 'STORE_CREATE_KIOSK_REQUEST';
export const STORE_CREATE_KIOSK_REQUEST_SUCCESS = 'STORE_CREATE_KIOSK_REQUEST_SUCCESS';
export const STORE_CREATE_KIOSK_REQUEST_ERROR = 'STORE_CREATE_KIOSK_REQUEST_ERROR';

export const STORE_GET_KIOSKS_REQUEST = 'STORE_GET_KIOSKS_REQUEST';
export const STORE_GET_KIOSKS_REQUEST_SUCCESS = 'STORE_GET_KIOSKS_REQUEST_SUCCESS';
export const STORE_GET_KIOSKS_REQUEST_ERROR = 'STORE_GET_KIOSKS_REQUEST_ERROR';
