export const STORE_CREATE_MEAL_REQUEST = 'STORE_CREATE_MEAL_REQUEST';
export const STORE_CREATE_MEAL_REQUEST_SUCCESS = 'STORE_CREATE_MEAL_REQUEST_SUCCESS';
export const STORE_CREATE_MEAL_REQUEST_ERROR = 'STORE_CREATE_MEAL_REQUEST_ERROR';

export const STORE_ADD_MEAL_PICTURE_REQUEST = 'STORE_ADD_MEAL_PICTURE_REQUEST';
export const STORE_ADD_MEAL_PICTURE_REQUEST_SUCCESS = 'STORE_ADD_MEAL_PICTURE_REQUEST_SUCCESS';
export const STORE_ADD_MEAL_PICTURE_REQUEST_ERROR = 'STORE_ADD_MEAL_PICTURE_REQUEST_ERROR';

export const STORE_GET_MEALS_REQUEST = 'STORE_GET_MEALS_REQUEST';
export const STORE_GET_MEALS_REQUEST_SUCCESS = 'STORE_GET_MEALS_REQUEST_SUCCESS';
export const STORE_GET_MEALS_REQUEST_ERROR = 'STORE_GET_MEALS_REQUEST_ERROR';

export const STORE_GET_MEAL_REQUEST = 'STORE_GET_MEAL_REQUEST';
export const STORE_GET_MEAL_REQUEST_SUCCESS = 'STORE_GET_MEAL_REQUEST_SUCCESS';
export const STORE_GET_MEAL_REQUEST_ERROR = 'STORE_GET_MEAL_REQUEST_ERROR';

export const STORE_DELETE_MEAL_REQUEST = 'STORE_DELETE_MEAL_REQUEST';
export const STORE_DELETE_MEAL_REQUEST_SUCCESS = 'STORE_DELETE_MEAL_REQUEST_SUCCESS';
export const STORE_DELETE_MEAL_REQUEST_ERROR = 'STORE_DELETE_MEAL_REQUEST_ERROR';

export const STORE_UPDATE_MEAL_REQUEST = 'STORE_UPDATE_MEAL_REQUEST';
export const STORE_UPDATE_MEAL_REQUEST_SUCCESS = 'STORE_UPDATE_MEAL_REQUEST_SUCCESS';
export const STORE_UPDATE_MEAL_REQUEST_ERROR = 'STORE_UPDATE_MEAL_REQUEST_ERROR';
